#!/bin/bash

mkdir -p build
cd build

`which lsb_release` && id=`lsb_release -si` && rel=`lsb_release -sr | sed 's/\..*//'`

if [ "$id" == "Ubuntu" ]; then
    if [ "$rel" == "20" ]; then
        # For Ubuntu 20
        cmake .. -DGR_PYTHON_DIR=/usr/local/lib/python3.8/dist-packages
    elif [ "$rel" == "18" ]; then
        # For Ubuntu 18
        cmake .. -DGR_PYTHON_DIR=/usr/local/lib/python3.6/dist-packages
    fi
else
    cmake ..
fi

cd ..
make -C build

sudo make -C build install
sudo ldconfig
